### ISSUE TITLE
[bug #19889] Need libusb version check in configure.

### ISSUE THREAD

**Issue by avrdude-admin** [avrdudes/avrdude#98]
Eric Weddington <None>
Thu 17 May 2007 02:33:15 PM UTC

avrdude 5.4 build is broken on Cygwin:

if gcc -DHAVE_CONFIG_H -I. -I../avrdude-5.4 -I.  -DCONFIG_DIR=\"c:/WinAVR/bin\" -I../../libusb-win32-device-bin-0.1.10.1/include -Wall -I../../libusb-win32-device-bin-0.1.10.1/include -mno-cygwin -DWIN32NATIVE -MT libavrdude_a-usb_libusb.o -MD -MP -MF ".deps/libavrdude_a-usb_libusb.Tpo" -c -o libavrdude_a-usb_libusb.o `test -f 'usb_libusb.c' || echo '../avrdude-5.4/'`usb_libusb.c; \
then mv -f ".deps/libavrdude_a-usb_libusb.Tpo" ".deps/libavrdude_a-usb_libusb.Po"; else rm -f ".deps/libavrdude_a-usb_libusb.Tpo"; exit 1; fi
../avrdude-5.4/usb_libusb.c: In function `usbdev_open':
../avrdude-5.4/usb_libusb.c:181: error: parse error before "struct"
make[1]: *** [libavrdude_a-usb_libusb.o] Error 1
make[1]: Target `install-am' not remade because of errors.
make[1]: Leaving directory `/cygdrive/c/avrdev/avrdude/build'
make: *** [install-recursive] Error 1
make: Target `install' not remade because of errors.

This issue was migrated from https://savannah.nongnu.org/bugs/?19889

**Comment by avrdude-admin** [comment]
Eric Weddington <arcanum>
Thu 17 May 2007 03:09:11 PM UTC

The build is broken using libusb 0.1.10.1, but the build works using libusb 0.1.12.1. There needs to be some way to do a configure check for the correct library version.

**Comment by avrdude-admin** [comment]
Joerg Wunsch <joerg_wunsch>
Thu 15 Sep 2011 04:10:24 PM UTC

Now checking for usb_get_string_simple rather than libusb_init,
this should ensure the right (minimum) version of libusb is
being probed.
